//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APILastBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public int Masach { get; set; }
        public string Tensach { get; set; }
        public string Tacgia { get; set; }
        public string Nhaxuatban { get; set; }
        public Nullable<System.DateTime> Namxb { get; set; }
    }
}
